export const INVALID_ARGS_NUMBER = "NAME is necessary";
export const USAGE_HEADER = "USAGE:";
export const USAGE = "  nameable [NAME] [OPTION]";
export const HELP_HINT = "For more information try --help";
export const INVALID_SILENT_ARGS = "Invalid args: silent";
export const INVALID_JSON_ARGS = "Invalid args: json";
export const INVALID_LANGUAGE_ARGS = "Invalid args: language";
export const INVALID_LANGUAGE_MEMBERS = "Invalid language:";
export const INVALID_ARGS_MEMBER = "Invalid query member";
