// Copyright 2021-present the Nameable authors. All rights reserved. MIT license.
export {
  and,
  entries,
  first,
  flattenDeep,
  has,
  ifElse,
  isArray,
  isBoolean,
  isString,
  isUndefined,
  keys,
  length,
  map,
  N,
  NN,
  or,
  props,
} from "https://deno.land/x/fonction@v1.7.0/mod.ts";
